//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using FacturacionElectronica;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISICFEEmisor", Namespace="http://tempuri.org/")]
public partial class ImpSICFEEmisor : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback EnvioCFEOperationCompleted;
    
    private System.Threading.SendOrPostCallback ValidarEnvioCFEOperationCompleted;
    
    private System.Threading.SendOrPostCallback RechazarCFERecibidoOperationCompleted;
    
    private System.Threading.SendOrPostCallback AceptarCFERecibidoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObtenerEventosOperationCompleted;
    
    private System.Threading.SendOrPostCallback ConfirmarEventosOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObtenerPDFOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObtenerRecursosImpresionOperationCompleted;
    
    private System.Threading.SendOrPostCallback ReimprimirOperationCompleted;
    
    private System.Threading.SendOrPostCallback AnularRangoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObtenerEstadoCFEOperationCompleted;
    
    /// <remarks/>
    public ImpSICFEEmisor() {
        this.Url = "http://190.64.89.202/SICFEServices/sicfe.svc";
    }

    public ImpSICFEEmisor(string pRutaWS)
    {
        if (!String.IsNullOrEmpty(pRutaWS.ToString()))
            this.Url =pRutaWS.ToString();
    }

    /// <remarks/>
    public event EnvioCFECompletedEventHandler EnvioCFECompleted;
    
    /// <remarks/>
    public event ValidarEnvioCFECompletedEventHandler ValidarEnvioCFECompleted;
    
    /// <remarks/>
    public event RechazarCFERecibidoCompletedEventHandler RechazarCFERecibidoCompleted;
    
    /// <remarks/>
    public event AceptarCFERecibidoCompletedEventHandler AceptarCFERecibidoCompleted;
    
    /// <remarks/>
    public event ObtenerEventosCompletedEventHandler ObtenerEventosCompleted;
    
    /// <remarks/>
    public event ConfirmarEventosCompletedEventHandler ConfirmarEventosCompleted;
    
    /// <remarks/>
    public event ObtenerPDFCompletedEventHandler ObtenerPDFCompleted;
    
    /// <remarks/>
    public event ObtenerRecursosImpresionCompletedEventHandler ObtenerRecursosImpresionCompleted;
    
    /// <remarks/>
    public event ReimprimirCompletedEventHandler ReimprimirCompleted;
    
    /// <remarks/>
    public event AnularRangoCompletedEventHandler AnularRangoCompleted;
    
    /// <remarks/>
    public event ObtenerEstadoCFECompletedEventHandler ObtenerEstadoCFECompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/EnvioCFE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuestaEnvioCFE EnvioCFE(
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string nomusuario,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string clave,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string tenant,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string cliente,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string cfexml,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string referenciaERP,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string referenciaERP2,
                bool devolverQR,
                int sizeQR,
                int imprime,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string recurso,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string template,
                bool devolverXML,
                bool erpPideValidacion,
                [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string version)
    {
        object[] results = this.Invoke("EnvioCFE", new object[] {
                    nomusuario,
                    clave,
                    tenant,
                    cliente,
                    cfexml,
                    referenciaERP,
                    referenciaERP2,
                    devolverQR,
                    sizeQR,
                    imprime,
                    recurso,
                    template,
                    devolverXML,
                    erpPideValidacion,
                    version});
        return ((SICFERespuestaEnvioCFE)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginEnvioCFE(
                string nomusuario,
                string clave,
                string tenant,
                string cliente,
                string cfexml,
                string referenciaERP,
                string referenciaERP2,
                bool devolverQR,
                int sizeQR,
                int imprime,
                string recurso,
                string template,
                bool devolverXML,
                bool erpPideValidacion,
                string version,
                System.AsyncCallback callback,
                object asyncState)
    {
        return this.BeginInvoke("EnvioCFE", new object[] {
                    nomusuario,
                    clave,
                    tenant,
                    cliente,
                    cfexml,
                    referenciaERP,
                    referenciaERP2,
                    devolverQR,
                    sizeQR,
                    imprime,
                    recurso,
                    template,
                    devolverXML,
                    erpPideValidacion,
                    version}, callback, asyncState);
    }

    /// <remarks/>
    public SICFERespuestaEnvioCFE EndEnvioCFE(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuestaEnvioCFE)(results[0]));
    }

    /// <remarks/>
    public void EnvioCFEAsync(
                string nomusuario,
                string clave,
                string tenant,
                string cliente,
                string cfexml,
                string referenciaERP,
                string referenciaERP2,
                bool devolverQR,
                int sizeQR,
                int imprime,
                string recurso,
                string template,
                bool devolverXML,
                bool erpPideValidacion,
                string version)
    {
        this.EnvioCFEAsync(nomusuario, clave, tenant, cliente, cfexml, referenciaERP, referenciaERP2, devolverQR, sizeQR, imprime, recurso, template, devolverXML, erpPideValidacion, version, null);
    }

    /// <remarks/>
    public void EnvioCFEAsync(
                string nomusuario,
                string clave,
                string tenant,
                string cliente,
                string cfexml,
                string referenciaERP,
                string referenciaERP2,
                bool devolverQR,
                int sizeQR,
                int imprime,
                string recurso,
                string template,
                bool devolverXML,
                bool erpPideValidacion,
                string version,
                object userState)
    {
        if ((this.EnvioCFEOperationCompleted == null))
        {
            this.EnvioCFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvioCFEOperationCompleted);
        }
        this.InvokeAsync("EnvioCFE", new object[] {
                    nomusuario,
                    clave,
                    tenant,
                    cliente,
                    cfexml,
                    referenciaERP,
                    referenciaERP2,
                    devolverQR,
                    sizeQR,
                    imprime,
                    recurso,
                    template,
                    devolverXML,
                    erpPideValidacion,
                    version}, this.EnvioCFEOperationCompleted, userState);
    }
    ////public SICFERespuestaEnvioCFE EnvioCFE(
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tenant, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cliente, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfexml, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenciaERP, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenciaERP2, 
    ////            bool devolverQR, 
    ////            [System.Xml.Serialization.XmlIgnoreAttribute()] bool devolverQRSpecified, 
    ////            int sizeQR, 
    ////            [System.Xml.Serialization.XmlIgnoreAttribute()] bool sizeQRSpecified, 
    ////            int imprime, 
    ////            [System.Xml.Serialization.XmlIgnoreAttribute()] bool imprimeSpecified, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string recurso, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string template, 
    ////            bool devolverXML, 
    ////            [System.Xml.Serialization.XmlIgnoreAttribute()] bool devolverXMLSpecified, 
    ////            bool erpPideValidacion, 
    ////            [System.Xml.Serialization.XmlIgnoreAttribute()] bool erpPideValidacionSpecified, 
    ////            [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string version) {
    ////    object[] results = this.Invoke("EnvioCFE", new object[] {
    ////                nomusuario,
    ////                clave,
    ////                tenant,
    ////                cliente,
    ////                cfexml,
    ////                referenciaERP,
    ////                referenciaERP2,
    ////                devolverQR,
    ////                devolverQRSpecified,
    ////                sizeQR,
    ////                sizeQRSpecified,
    ////                imprime,
    ////                imprimeSpecified,
    ////                recurso,
    ////                template,
    ////                devolverXML,
    ////                devolverXMLSpecified,
    ////                erpPideValidacion,
    ////                erpPideValidacionSpecified,
    ////                version});
    ////    return ((SICFERespuestaEnvioCFE)(results[0]));
    ////}
    
    /////// <remarks/>
    ////public System.IAsyncResult BeginEnvioCFE(
    ////            string nomusuario, 
    ////            string clave, 
    ////            string tenant, 
    ////            string cliente, 
    ////            string cfexml, 
    ////            string referenciaERP, 
    ////            string referenciaERP2, 
    ////            bool devolverQR, 
    ////            bool devolverQRSpecified, 
    ////            int sizeQR, 
    ////            bool sizeQRSpecified, 
    ////            int imprime, 
    ////            bool imprimeSpecified, 
    ////            string recurso, 
    ////            string template, 
    ////            bool devolverXML, 
    ////            bool devolverXMLSpecified, 
    ////            bool erpPideValidacion, 
    ////            bool erpPideValidacionSpecified, 
    ////            string version, 
    ////            System.AsyncCallback callback, 
    ////            object asyncState) {
    ////    return this.BeginInvoke("EnvioCFE", new object[] {
    ////                nomusuario,
    ////                clave,
    ////                tenant,
    ////                cliente,
    ////                cfexml,
    ////                referenciaERP,
    ////                referenciaERP2,
    ////                devolverQR,
    ////                devolverQRSpecified,
    ////                sizeQR,
    ////                sizeQRSpecified,
    ////                imprime,
    ////                imprimeSpecified,
    ////                recurso,
    ////                template,
    ////                devolverXML,
    ////                devolverXMLSpecified,
    ////                erpPideValidacion,
    ////                erpPideValidacionSpecified,
    ////                version}, callback, asyncState);
    ////}
    
    /////// <remarks/>
    ////public SICFERespuestaEnvioCFE EndEnvioCFE(System.IAsyncResult asyncResult) {
    ////    object[] results = this.EndInvoke(asyncResult);
    ////    return ((SICFERespuestaEnvioCFE)(results[0]));
    ////}
    
    /////// <remarks/>
    ////public void EnvioCFEAsync(
    ////            string nomusuario, 
    ////            string clave, 
    ////            string tenant, 
    ////            string cliente, 
    ////            string cfexml, 
    ////            string referenciaERP, 
    ////            string referenciaERP2, 
    ////            bool devolverQR, 
    ////            bool devolverQRSpecified, 
    ////            int sizeQR, 
    ////            bool sizeQRSpecified, 
    ////            int imprime, 
    ////            bool imprimeSpecified, 
    ////            string recurso, 
    ////            string template, 
    ////            bool devolverXML, 
    ////            bool devolverXMLSpecified, 
    ////            bool erpPideValidacion, 
    ////            bool erpPideValidacionSpecified, 
    ////            string version) {
    ////    this.EnvioCFEAsync(nomusuario, clave, tenant, cliente, cfexml, referenciaERP, referenciaERP2, devolverQR, devolverQRSpecified, sizeQR, sizeQRSpecified, imprime, imprimeSpecified, recurso, template, devolverXML, devolverXMLSpecified, erpPideValidacion, erpPideValidacionSpecified, version, null);
    ////}
    
    /////// <remarks/>
    ////public void EnvioCFEAsync(
    ////            string nomusuario, 
    ////            string clave, 
    ////            string tenant, 
    ////            string cliente, 
    ////            string cfexml, 
    ////            string referenciaERP, 
    ////            string referenciaERP2, 
    ////            bool devolverQR, 
    ////            bool devolverQRSpecified, 
    ////            int sizeQR, 
    ////            bool sizeQRSpecified, 
    ////            int imprime, 
    ////            bool imprimeSpecified, 
    ////            string recurso, 
    ////            string template, 
    ////            bool devolverXML, 
    ////            bool devolverXMLSpecified, 
    ////            bool erpPideValidacion, 
    ////            bool erpPideValidacionSpecified, 
    ////            string version, 
    ////            object userState) {
    ////    if ((this.EnvioCFEOperationCompleted == null)) {
    ////        this.EnvioCFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvioCFEOperationCompleted);
    ////    }
    ////    this.InvokeAsync("EnvioCFE", new object[] {
    ////                nomusuario,
    ////                clave,
    ////                tenant,
    ////                cliente,
    ////                cfexml,
    ////                referenciaERP,
    ////                referenciaERP2,
    ////                devolverQR,
    ////                devolverQRSpecified,
    ////                sizeQR,
    ////                sizeQRSpecified,
    ////                imprime,
    ////                imprimeSpecified,
    ////                recurso,
    ////                template,
    ////                devolverXML,
    ////                devolverXMLSpecified,
    ////                erpPideValidacion,
    ////                erpPideValidacionSpecified,
    ////                version}, this.EnvioCFEOperationCompleted, userState);
    ////}
    
    private void OnEnvioCFEOperationCompleted(object arg) {
        if ((this.EnvioCFECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EnvioCFECompleted(this, new EnvioCFECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/ValidarEnvioCFE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuestaEnvioCFE ValidarEnvioCFE([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tenant, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cliente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfexml, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string version) {
        object[] results = this.Invoke("ValidarEnvioCFE", new object[] {
                    nomusuario,
                    clave,
                    tenant,
                    cliente,
                    cfexml,
                    version});
        return ((SICFERespuestaEnvioCFE)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginValidarEnvioCFE(string nomusuario, string clave, string tenant, string cliente, string cfexml, string version, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ValidarEnvioCFE", new object[] {
                    nomusuario,
                    clave,
                    tenant,
                    cliente,
                    cfexml,
                    version}, callback, asyncState);
    }
    
    /// <remarks/>
    public SICFERespuestaEnvioCFE EndValidarEnvioCFE(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuestaEnvioCFE)(results[0]));
    }
    
    /// <remarks/>
    public void ValidarEnvioCFEAsync(string nomusuario, string clave, string tenant, string cliente, string cfexml, string version) {
        this.ValidarEnvioCFEAsync(nomusuario, clave, tenant, cliente, cfexml, version, null);
    }
    
    /// <remarks/>
    public void ValidarEnvioCFEAsync(string nomusuario, string clave, string tenant, string cliente, string cfexml, string version, object userState) {
        if ((this.ValidarEnvioCFEOperationCompleted == null)) {
            this.ValidarEnvioCFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarEnvioCFEOperationCompleted);
        }
        this.InvokeAsync("ValidarEnvioCFE", new object[] {
                    nomusuario,
                    clave,
                    tenant,
                    cliente,
                    cfexml,
                    version}, this.ValidarEnvioCFEOperationCompleted, userState);
    }
    
    private void OnValidarEnvioCFEOperationCompleted(object arg) {
        if ((this.ValidarEnvioCFECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ValidarEnvioCFECompleted(this, new ValidarEnvioCFECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/RechazarCFERecibido", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public SICFERespuesta RechazarCFERecibido([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string param_tenant, long p_rucEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] IdCFE p_idCFE, [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/SICFEContract")] RechazoAcuseRecibo[] p_motivosRechazo)
    {
        object[] results = this.Invoke("RechazarCFERecibido", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_rucEmisor,
                    p_idCFE,
                    p_motivosRechazo});
        return ((SICFERespuesta)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginRechazarCFERecibido(string nomusuario, string clave, string param_tenant, long p_rucEmisor, IdCFE p_idCFE, RechazoAcuseRecibo[] p_motivosRechazo, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("RechazarCFERecibido", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_rucEmisor,
                    p_idCFE,
                    p_motivosRechazo}, callback, asyncState);
    }

    ///////// <remarks/>
    //////[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/RechazarCFERecibido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    //////[return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    //////public SICFERespuesta RechazarCFERecibido([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string param_tenant, long p_rucEmisor, [XSystem.ml.Serialization.XmlIgnoreAttribute()] bool p_rucEmisorSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IdCFE p_idCFE, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")] RechazoAcuseRecibo[] p_motivosRechazo) {
    //////    object[] results = this.Invoke("RechazarCFERecibido", new object[] {
    //////                nomusuario,
    //////                clave,
    //////                param_tenant,
    //////                p_rucEmisor,
    //////                p_rucEmisorSpecified,
    //////                p_idCFE,
    //////                p_motivosRechazo});
    //////    return ((SICFERespuesta)(results[0]));
    //////}
    
    ///////// <remarks/>
    //////public System.IAsyncResult BeginRechazarCFERecibido(string nomusuario, string clave, string param_tenant, long p_rucEmisor, bool p_rucEmisorSpecified, IdCFE p_idCFE, RechazoAcuseRecibo[] p_motivosRechazo, System.AsyncCallback callback, object asyncState) {
    //////    return this.BeginInvoke("RechazarCFERecibido", new object[] {
    //////                nomusuario,
    //////                clave,
    //////                param_tenant,
    //////                p_rucEmisor,
    //////                p_rucEmisorSpecified,
    //////                p_idCFE,
    //////                p_motivosRechazo}, callback, asyncState);
    //////}
    
    /// <remarks/>
    public SICFERespuesta EndRechazarCFERecibido(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public void RechazarCFERecibidoAsync(string nomusuario, string clave, string param_tenant, long p_rucEmisor, bool p_rucEmisorSpecified, IdCFE p_idCFE, RechazoAcuseRecibo[] p_motivosRechazo) {
        this.RechazarCFERecibidoAsync(nomusuario, clave, param_tenant, p_rucEmisor, p_rucEmisorSpecified, p_idCFE, p_motivosRechazo, null);
    }
    
    /// <remarks/>
    public void RechazarCFERecibidoAsync(string nomusuario, string clave, string param_tenant, long p_rucEmisor, bool p_rucEmisorSpecified, IdCFE p_idCFE, RechazoAcuseRecibo[] p_motivosRechazo, object userState) {
        if ((this.RechazarCFERecibidoOperationCompleted == null)) {
            this.RechazarCFERecibidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRechazarCFERecibidoOperationCompleted);
        }
        this.InvokeAsync("RechazarCFERecibido", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_rucEmisor,
                    p_rucEmisorSpecified,
                    p_idCFE,
                    p_motivosRechazo}, this.RechazarCFERecibidoOperationCompleted, userState);
    }
    
    private void OnRechazarCFERecibidoOperationCompleted(object arg) {
        if ((this.RechazarCFERecibidoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RechazarCFERecibidoCompleted(this, new RechazarCFERecibidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/AceptarCFERecibido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuesta AceptarCFERecibido([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string param_tenant, long p_rucEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IdCFE p_idCFE) {
        object[] results = this.Invoke("AceptarCFERecibido", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_rucEmisor,
                    p_idCFE});
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAceptarCFERecibido(string nomusuario, string clave, string param_tenant, long p_rucEmisor, bool p_rucEmisorSpecified, IdCFE p_idCFE, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AceptarCFERecibido", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_rucEmisor,
                    p_rucEmisorSpecified,
                    p_idCFE}, callback, asyncState);
    }
    
    /// <remarks/>
    public SICFERespuesta EndAceptarCFERecibido(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public void AceptarCFERecibidoAsync(string nomusuario, string clave, string param_tenant, long p_rucEmisor, bool p_rucEmisorSpecified, IdCFE p_idCFE) {
        this.AceptarCFERecibidoAsync(nomusuario, clave, param_tenant, p_rucEmisor, p_rucEmisorSpecified, p_idCFE, null);
    }
    
    /// <remarks/>
    public void AceptarCFERecibidoAsync(string nomusuario, string clave, string param_tenant, long p_rucEmisor, bool p_rucEmisorSpecified, IdCFE p_idCFE, object userState) {
        if ((this.AceptarCFERecibidoOperationCompleted == null)) {
            this.AceptarCFERecibidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAceptarCFERecibidoOperationCompleted);
        }
        this.InvokeAsync("AceptarCFERecibido", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_rucEmisor,
                    p_rucEmisorSpecified,
                    p_idCFE}, this.AceptarCFERecibidoOperationCompleted, userState);
    }
    
    private void OnAceptarCFERecibidoOperationCompleted(object arg) {
        if ((this.AceptarCFERecibidoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AceptarCFERecibidoCompleted(this, new AceptarCFERecibidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/ObtenerEventos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public RespuestaObtenerEventos ObtenerEventos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string param_tenant, int cuantos) {
        object[] results = this.Invoke("ObtenerEventos", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    cuantos});
        return ((RespuestaObtenerEventos)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObtenerEventos(string nomusuario, string clave, string param_tenant, int cuantos, bool cuantosSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObtenerEventos", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    cuantos,
                    cuantosSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public RespuestaObtenerEventos EndObtenerEventos(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RespuestaObtenerEventos)(results[0]));
    }
    
    /// <remarks/>
    public void ObtenerEventosAsync(string nomusuario, string clave, string param_tenant, int cuantos, bool cuantosSpecified) {
        this.ObtenerEventosAsync(nomusuario, clave, param_tenant, cuantos, cuantosSpecified, null);
    }
    
    /// <remarks/>
    public void ObtenerEventosAsync(string nomusuario, string clave, string param_tenant, int cuantos, bool cuantosSpecified, object userState) {
        if ((this.ObtenerEventosOperationCompleted == null)) {
            this.ObtenerEventosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEventosOperationCompleted);
        }
        this.InvokeAsync("ObtenerEventos", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    cuantos,
                    cuantosSpecified}, this.ObtenerEventosOperationCompleted, userState);
    }
    
    private void OnObtenerEventosOperationCompleted(object arg) {
        if ((this.ObtenerEventosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerEventosCompleted(this, new ObtenerEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/ConfirmarEventos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuesta ConfirmarEventos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string param_tenant, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] long[] confirmados) {
        object[] results = this.Invoke("ConfirmarEventos", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    confirmados});
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginConfirmarEventos(string nomusuario, string clave, string param_tenant, long[] confirmados, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ConfirmarEventos", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    confirmados}, callback, asyncState);
    }
    
    /// <remarks/>
    public SICFERespuesta EndConfirmarEventos(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public void ConfirmarEventosAsync(string nomusuario, string clave, string param_tenant, long[] confirmados) {
        this.ConfirmarEventosAsync(nomusuario, clave, param_tenant, confirmados, null);
    }
    
    /// <remarks/>
    public void ConfirmarEventosAsync(string nomusuario, string clave, string param_tenant, long[] confirmados, object userState) {
        if ((this.ConfirmarEventosOperationCompleted == null)) {
            this.ConfirmarEventosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarEventosOperationCompleted);
        }
        this.InvokeAsync("ConfirmarEventos", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    confirmados}, this.ConfirmarEventosOperationCompleted, userState);
    }
    
    private void OnConfirmarEventosOperationCompleted(object arg) {
        if ((this.ConfirmarEventosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ConfirmarEventosCompleted(this, new ConfirmarEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/ObtenerPDF", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public SICFERespuestaBuffer ObtenerPDF([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] IdCFE p_idCFE, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string p_tenant, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string template)
    {
        object[] results = this.Invoke("ObtenerPDF", new object[] {
                    nomusuario,
                    clave,
                    p_idCFE,
                    p_tenant,
                    template});
        return ((SICFERespuestaBuffer)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginObtenerPDF(string nomusuario, string clave, IdCFE p_idCFE, string p_tenant, string template, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ObtenerPDF", new object[] {
                    nomusuario,
                    clave,
                    p_idCFE,
                    p_tenant,
                    template}, callback, asyncState);
    }

    /// <remarks/>
    public SICFERespuestaBuffer EndObtenerPDF(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuestaBuffer)(results[0]));
    }

    /// <remarks/>
    public void ObtenerPDFAsync(string nomusuario, string clave, IdCFE p_idCFE, string p_tenant, string template)
    {
        this.ObtenerPDFAsync(nomusuario, clave, p_idCFE, p_tenant, template, null);
    }

    /// <remarks/>
    public void ObtenerPDFAsync(string nomusuario, string clave, IdCFE p_idCFE, string p_tenant, string template, object userState)
    {
        if ((this.ObtenerPDFOperationCompleted == null))
        {
            this.ObtenerPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPDFOperationCompleted);
        }
        this.InvokeAsync("ObtenerPDF", new object[] {
                    nomusuario,
                    clave,
                    p_idCFE,
                    p_tenant,
                    template}, this.ObtenerPDFOperationCompleted, userState);
    }

    private void OnObtenerPDFOperationCompleted(object arg)
    {
        if ((this.ObtenerPDFCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerPDFCompleted(this, new ObtenerPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/ObtenerRecursosImpresion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public RespuestaObtenerRecursosImpresion ObtenerRecursosImpresion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tenant) {
        object[] results = this.Invoke("ObtenerRecursosImpresion", new object[] {
                    nomusuario,
                    clave,
                    tenant});
        return ((RespuestaObtenerRecursosImpresion)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObtenerRecursosImpresion(string nomusuario, string clave, string tenant, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObtenerRecursosImpresion", new object[] {
                    nomusuario,
                    clave,
                    tenant}, callback, asyncState);
    }
    
    /// <remarks/>
    public RespuestaObtenerRecursosImpresion EndObtenerRecursosImpresion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RespuestaObtenerRecursosImpresion)(results[0]));
    }
    
    /// <remarks/>
    public void ObtenerRecursosImpresionAsync(string nomusuario, string clave, string tenant) {
        this.ObtenerRecursosImpresionAsync(nomusuario, clave, tenant, null);
    }
    
    /// <remarks/>
    public void ObtenerRecursosImpresionAsync(string nomusuario, string clave, string tenant, object userState) {
        if ((this.ObtenerRecursosImpresionOperationCompleted == null)) {
            this.ObtenerRecursosImpresionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerRecursosImpresionOperationCompleted);
        }
        this.InvokeAsync("ObtenerRecursosImpresion", new object[] {
                    nomusuario,
                    clave,
                    tenant}, this.ObtenerRecursosImpresionOperationCompleted, userState);
    }
    
    private void OnObtenerRecursosImpresionOperationCompleted(object arg) {
        if ((this.ObtenerRecursosImpresionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerRecursosImpresionCompleted(this, new ObtenerRecursosImpresionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/Reimprimir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuestaReimpresion Reimprimir([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string param_tenant, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IdCFE p_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string impresora, int nroImpresiones, string template) {
        object[] results = this.Invoke("Reimprimir", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_ID,
                    impresora,
                    nroImpresiones,
                    template});
        return ((SICFERespuestaReimpresion)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginReimprimir(string nomusuario, string clave, string param_tenant, IdCFE p_ID, string impresora, int nroImpresiones, bool nroImpresionesSpecified, string template, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("Reimprimir", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_ID,
                    impresora,
                    nroImpresiones,
                    nroImpresionesSpecified,
                    template}, callback, asyncState);
    }
    
    /// <remarks/>
    public SICFERespuestaReimpresion EndReimprimir(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuestaReimpresion)(results[0]));
    }
    
    /// <remarks/>
    public void ReimprimirAsync(string nomusuario, string clave, string param_tenant, IdCFE p_ID, string impresora, int nroImpresiones, bool nroImpresionesSpecified,string template) {
        this.ReimprimirAsync(nomusuario, clave, param_tenant, p_ID, impresora, nroImpresiones, nroImpresionesSpecified, null);
    }
    
    /// <remarks/>
    public void ReimprimirAsync(string nomusuario, string clave, string param_tenant, IdCFE p_ID, string impresora, int nroImpresiones, bool nroImpresionesSpecified,string template, object userState) {
        if ((this.ReimprimirOperationCompleted == null)) {
            this.ReimprimirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReimprimirOperationCompleted);
        }
        this.InvokeAsync("Reimprimir", new object[] {
                    nomusuario,
                    clave,
                    param_tenant,
                    p_ID,
                    impresora,
                    nroImpresiones,
                    nroImpresionesSpecified,
                    template}, this.ReimprimirOperationCompleted, userState);
    }
    
    private void OnReimprimirOperationCompleted(object arg) {
        if ((this.ReimprimirCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ReimprimirCompleted(this, new ReimprimirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/AnularRango", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuesta AnularRango([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nomusuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pass, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string param_tenant, int p_tipo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string p_serie, int p_desde, [System.Xml.Serialization.XmlIgnoreAttribute()] bool p_desdeSpecified, int p_hasta, int p_sucursal) {
        object[] results = this.Invoke("AnularRango", new object[] {
                    nomusuario,
                    pass,
                    param_tenant,
                    p_tipo,
                    p_serie,
                    p_desde,
                    p_desdeSpecified,
                    p_hasta,
                    p_sucursal});
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAnularRango(string nomusuario, string pass, string param_tenant, int p_tipo, bool p_tipoSpecified, string p_serie, int p_desde, bool p_desdeSpecified, int p_hasta, bool p_hastaSpecified, int p_sucursal, bool p_sucursalSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AnularRango", new object[] {
                    nomusuario,
                    pass,
                    param_tenant,
                    p_tipo,
                    p_tipoSpecified,
                    p_serie,
                    p_desde,
                    p_desdeSpecified,
                    p_hasta,
                    p_hastaSpecified,
                    p_sucursal,
                    p_sucursalSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public SICFERespuesta EndAnularRango(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuesta)(results[0]));
    }
    
    /// <remarks/>
    public void AnularRangoAsync(string nomusuario, string pass, string param_tenant, int p_tipo, bool p_tipoSpecified, string p_serie, int p_desde, bool p_desdeSpecified, int p_hasta, bool p_hastaSpecified, int p_sucursal, bool p_sucursalSpecified) {
        this.AnularRangoAsync(nomusuario, pass, param_tenant, p_tipo, p_tipoSpecified, p_serie, p_desde, p_desdeSpecified, p_hasta, p_hastaSpecified, p_sucursal, p_sucursalSpecified, null);
    }
    
    /// <remarks/>
    public void AnularRangoAsync(string nomusuario, string pass, string param_tenant, int p_tipo, bool p_tipoSpecified, string p_serie, int p_desde, bool p_desdeSpecified, int p_hasta, bool p_hastaSpecified, int p_sucursal, bool p_sucursalSpecified, object userState) {
        if ((this.AnularRangoOperationCompleted == null)) {
            this.AnularRangoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnularRangoOperationCompleted);
        }
        this.InvokeAsync("AnularRango", new object[] {
                    nomusuario,
                    pass,
                    param_tenant,
                    p_tipo,
                    p_tipoSpecified,
                    p_serie,
                    p_desde,
                    p_desdeSpecified,
                    p_hasta,
                    p_hastaSpecified,
                    p_sucursal,
                    p_sucursalSpecified}, this.AnularRangoOperationCompleted, userState);
    }
    
    private void OnAnularRangoOperationCompleted(object arg) {
        if ((this.AnularRangoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AnularRangoCompleted(this, new AnularRangoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISICFEEmisor/ObtenerEstadoCFE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SICFERespuestaEstadoCFE ObtenerEstadoCFE([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pUsuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pClave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pTenant, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IdCFE pIDCFE) {
        object[] results = this.Invoke("ObtenerEstadoCFE", new object[] {
                    pUsuario,
                    pClave,
                    pTenant,
                    pIDCFE});
        return ((SICFERespuestaEstadoCFE)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObtenerEstadoCFE(string pUsuario, string pClave, string pTenant, IdCFE pIDCFE, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObtenerEstadoCFE", new object[] {
                    pUsuario,
                    pClave,
                    pTenant,
                    pIDCFE}, callback, asyncState);
    }
    
    /// <remarks/>
    public SICFERespuestaEstadoCFE EndObtenerEstadoCFE(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SICFERespuestaEstadoCFE)(results[0]));
    }
    
    /// <remarks/>
    public void ObtenerEstadoCFEAsync(string pUsuario, string pClave, string pTenant, IdCFE pIDCFE) {
        this.ObtenerEstadoCFEAsync(pUsuario, pClave, pTenant, pIDCFE, null);
    }
    
    /// <remarks/>
    public void ObtenerEstadoCFEAsync(string pUsuario, string pClave, string pTenant, IdCFE pIDCFE, object userState) {
        if ((this.ObtenerEstadoCFEOperationCompleted == null)) {
            this.ObtenerEstadoCFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEstadoCFEOperationCompleted);
        }
        this.InvokeAsync("ObtenerEstadoCFE", new object[] {
                    pUsuario,
                    pClave,
                    pTenant,
                    pIDCFE}, this.ObtenerEstadoCFEOperationCompleted, userState);
    }
    
    private void OnObtenerEstadoCFEOperationCompleted(object arg) {
        if ((this.ObtenerEstadoCFECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerEstadoCFECompleted(this, new ObtenerEstadoCFECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class SICFERespuestaEnvioCFE : SICFERespuesta {
    
    private bool esReceptorElectronicoField;
    
    private bool esReceptorElectronicoFieldSpecified;
    
    private IdCFE idCFEField;
    
    private string imagenQRField;
    
    private string linkQRField;
    
    private datosCAE datosCAEField;
    
    private string hashField;
    
    private string xmlField;
    
    /// <comentarios/>
    public bool EsReceptorElectronico {
        get {
            return this.esReceptorElectronicoField;
        }
        set {
            this.esReceptorElectronicoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool EsReceptorElectronicoSpecified {
    ////    get {
    ////        return this.esReceptorElectronicoFieldSpecified;
    ////    }
    ////    set {
    ////        this.esReceptorElectronicoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IdCFE IdCFE {
        get {
            return this.idCFEField;
        }
        set {
            this.idCFEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ImagenQR {
        get {
            return this.imagenQRField;
        }
        set {
            this.imagenQRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string LinkQR {
        get {
            return this.linkQRField;
        }
        set {
            this.linkQRField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public datosCAE datosCAE {
        get {
            return this.datosCAEField;
        }
        set {
            this.datosCAEField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string xml {
        get {
            return this.xmlField;
        }
        set {
            this.xmlField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class IdCFE {
    
    private int numeroField;
    
    private bool numeroFieldSpecified;
    
    private string serieField;
    
    private int tipoField;
    
    private bool tipoFieldSpecified;
    
    private int observadoField;
    
    private bool observadoFieldSpecified;
    
    private string rucemisorField;
    
    /// <comentarios/>
    public int Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool NumeroSpecified {
    ////    get {
    ////        return this.numeroFieldSpecified;
    ////    }
    ////    set {
    ////        this.numeroFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Serie {
        get {
            return this.serieField;
        }
        set {
            this.serieField = value;
        }
    }
    
    /// <comentarios/>
    public int Tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool TipoSpecified {
    ////    get {
    ////        return this.tipoFieldSpecified;
    ////    }
    ////    set {
    ////        this.tipoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    public int observado {
        get {
            return this.observadoField;
        }
        set {
            this.observadoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool observadoSpecified {
    ////    get {
    ////        return this.observadoFieldSpecified;
    ////    }
    ////    set {
    ////        this.observadoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string rucemisor {
        get {
            return this.rucemisorField;
        }
        set {
            this.rucemisorField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class ResultadoReimpresion {
    
    private IdCFE cFEField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IdCFE CFE {
        get {
            return this.cFEField;
        }
        set {
            this.cFEField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class Impresora {
    
    private bool colorField;
    
    private bool colorFieldSpecified;
    
    private string nombreField;
    
    private string papelField;
    
    private bool porDefectoField;
    
    private bool porDefectoFieldSpecified;
    
    /// <comentarios/>
    public bool Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool ColorSpecified {
    ////    get {
    ////        return this.colorFieldSpecified;
    ////    }
    ////    set {
    ////        this.colorFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Papel {
        get {
            return this.papelField;
        }
        set {
            this.papelField = value;
        }
    }
    
    /// <comentarios/>
    public bool PorDefecto {
        get {
            return this.porDefectoField;
        }
        set {
            this.porDefectoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool PorDefectoSpecified {
    ////    get {
    ////        return this.porDefectoFieldSpecified;
    ////    }
    ////    set {
    ////        this.porDefectoFieldSpecified = value;
    ////    }
    ////}
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class RechazoAcuseRecibo {
    
    private string codigoField;
    
    private string descripcionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Codigo {
        get {
            return this.codigoField;
        }
        set {
            this.codigoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class EventoSICFE {
    
    private System.Nullable<long> eventHandlerField;
    
    private bool eventHandlerFieldSpecified;
    
    private RechazoAcuseRecibo[] listaMotivosRechazoField;
    
    private string codigoeventoField;
    
    private string descripcioneventoField;
    
    private System.Nullable<long> idEventoField;
    
    private bool idEventoFieldSpecified;
    
    private System.Nullable<int> numeroField;
    
    private bool numeroFieldSpecified;
    
    private System.Nullable<int> observadoField;
    
    private bool observadoFieldSpecified;
    
    private string referenciaerpField;
    
    private string rucemisorField;
    
    private string serieField;
    
    private System.Nullable<long> sobreField;
    
    private bool sobreFieldSpecified;
    
    private string tenantField;
    
    private System.Nullable<int> tipoCFEField;
    
    private bool tipoCFEFieldSpecified;
    
    private string xmlField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> EventHandler {
        get {
            return this.eventHandlerField;
        }
        set {
            this.eventHandlerField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool EventHandlerSpecified {
    ////    get {
    ////        return this.eventHandlerFieldSpecified;
    ////    }
    ////    set {
    ////        this.eventHandlerFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public RechazoAcuseRecibo[] ListaMotivosRechazo {
        get {
            return this.listaMotivosRechazoField;
        }
        set {
            this.listaMotivosRechazoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string codigoevento {
        get {
            return this.codigoeventoField;
        }
        set {
            this.codigoeventoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string descripcionevento {
        get {
            return this.descripcioneventoField;
        }
        set {
            this.descripcioneventoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> idEvento {
        get {
            return this.idEventoField;
        }
        set {
            this.idEventoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool idEventoSpecified {
    ////    get {
    ////        return this.idEventoFieldSpecified;
    ////    }
    ////    set {
    ////        this.idEventoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool numeroSpecified {
    ////    get {
    ////        return this.numeroFieldSpecified;
    ////    }
    ////    set {
    ////        this.numeroFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> observado {
        get {
            return this.observadoField;
        }
        set {
            this.observadoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool observadoSpecified {
    ////    get {
    ////        return this.observadoFieldSpecified;
    ////    }
    ////    set {
    ////        this.observadoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string referenciaerp {
        get {
            return this.referenciaerpField;
        }
        set {
            this.referenciaerpField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string rucemisor {
        get {
            return this.rucemisorField;
        }
        set {
            this.rucemisorField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string serie {
        get {
            return this.serieField;
        }
        set {
            this.serieField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> sobre {
        get {
            return this.sobreField;
        }
        set {
            this.sobreField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool sobreSpecified {
    ////    get {
    ////        return this.sobreFieldSpecified;
    ////    }
    ////    set {
    ////        this.sobreFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string tenant {
        get {
            return this.tenantField;
        }
        set {
            this.tenantField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> tipoCFE {
        get {
            return this.tipoCFEField;
        }
        set {
            this.tipoCFEField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool tipoCFESpecified {
    ////    get {
    ////        return this.tipoCFEFieldSpecified;
    ////    }
    ////    set {
    ////        this.tipoCFEFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string xml {
        get {
            return this.xmlField;
        }
        set {
            this.xmlField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class datosCAE {
    
    private System.Nullable<int> dnroField;
    
    private bool dnroFieldSpecified;
    
    private System.Nullable<System.DateTime> fvtoField;
    
    private bool fvtoFieldSpecified;
    
    private System.Nullable<int> hnroField;
    
    private bool hnroFieldSpecified;
    
    private System.Nullable<decimal> nautoField;
    
    private bool nautoFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> dnro {
        get {
            return this.dnroField;
        }
        set {
            this.dnroField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool dnroSpecified {
    ////    get {
    ////        return this.dnroFieldSpecified;
    ////    }
    ////    set {
    ////        this.dnroFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> fvto {
        get {
            return this.fvtoField;
        }
        set {
            this.fvtoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool fvtoSpecified {
    ////    get {
    ////        return this.fvtoFieldSpecified;
    ////    }
    ////    set {
    ////        this.fvtoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> hnro {
        get {
            return this.hnroField;
        }
        set {
            this.hnroField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool hnroSpecified {
    ////    get {
    ////        return this.hnroFieldSpecified;
    ////    }
    ////    set {
    ////        this.hnroFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> nauto {
        get {
            return this.nautoField;
        }
        set {
            this.nautoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool nautoSpecified {
    ////    get {
    ////        return this.nautoFieldSpecified;
    ////    }
    ////    set {
    ////        this.nautoFieldSpecified = value;
    ////    }
    ////}
}

/// <comentarios/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SICFERespuestaEstadoCFE))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SICFERespuestaReimpresion))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaObtenerRecursosImpresion))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SICFERespuestaBuffer))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaObtenerEventos))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SICFERespuestaEnvioCFE))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class SICFERespuesta {
    
    private int codigoField;
    
    private bool codigoFieldSpecified;
    
    private string descripcionField;
    
    /// <comentarios/>
    public int Codigo {
        get {
            return this.codigoField;
        }
        set {
            this.codigoField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool CodigoSpecified {
    ////    get {
    ////        return this.codigoFieldSpecified;
    ////    }
    ////    set {
    ////        this.codigoFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class SICFERespuestaEstadoCFE : SICFERespuesta {
    
    private string estadoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Estado {
        get {
            return this.estadoField;
        }
        set {
            this.estadoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class SICFERespuestaReimpresion : SICFERespuesta {
    
    private ResultadoReimpresion[] resultadosPorCFEField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public ResultadoReimpresion[] ResultadosPorCFE {
        get {
            return this.resultadosPorCFEField;
        }
        set {
            this.resultadosPorCFEField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class RespuestaObtenerRecursosImpresion : SICFERespuesta {
    
    private Impresora[] listRecursosImpresionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public Impresora[] ListRecursosImpresion {
        get {
            return this.listRecursosImpresionField;
        }
        set {
            this.listRecursosImpresionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class SICFERespuestaBuffer : SICFERespuesta {
    
    private byte[] bufferField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] Buffer {
        get {
            return this.bufferField;
        }
        set {
            this.bufferField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SICFEContract")]
public partial class RespuestaObtenerEventos : SICFERespuesta {
    
    private bool hayMasRegistrosField;
    
    private bool hayMasRegistrosFieldSpecified;
    
    private EventoSICFE[] listEventoSICFEField;
    
    /// <comentarios/>
    public bool HayMasRegistros {
        get {
            return this.hayMasRegistrosField;
        }
        set {
            this.hayMasRegistrosField = value;
        }
    }
    
    /////// <comentarios/>
    ////[System.Xml.Serialization.XmlIgnoreAttribute()]
    ////public bool HayMasRegistrosSpecified {
    ////    get {
    ////        return this.hayMasRegistrosFieldSpecified;
    ////    }
    ////    set {
    ////        this.hayMasRegistrosFieldSpecified = value;
    ////    }
    ////}
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public EventoSICFE[] ListEventoSICFE {
        get {
            return this.listEventoSICFEField;
        }
        set {
            this.listEventoSICFEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void EnvioCFECompletedEventHandler(object sender, EnvioCFECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EnvioCFECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EnvioCFECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuestaEnvioCFE Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuestaEnvioCFE)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ValidarEnvioCFECompletedEventHandler(object sender, ValidarEnvioCFECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ValidarEnvioCFECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ValidarEnvioCFECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuestaEnvioCFE Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuestaEnvioCFE)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void RechazarCFERecibidoCompletedEventHandler(object sender, RechazarCFERecibidoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RechazarCFERecibidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RechazarCFERecibidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuesta Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuesta)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AceptarCFERecibidoCompletedEventHandler(object sender, AceptarCFERecibidoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AceptarCFERecibidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AceptarCFERecibidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuesta Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuesta)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ObtenerEventosCompletedEventHandler(object sender, ObtenerEventosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerEventosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObtenerEventosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RespuestaObtenerEventos Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RespuestaObtenerEventos)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ConfirmarEventosCompletedEventHandler(object sender, ConfirmarEventosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ConfirmarEventosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ConfirmarEventosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuesta Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuesta)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ObtenerPDFCompletedEventHandler(object sender, ObtenerPDFCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObtenerPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuestaBuffer Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuestaBuffer)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ObtenerRecursosImpresionCompletedEventHandler(object sender, ObtenerRecursosImpresionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerRecursosImpresionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObtenerRecursosImpresionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RespuestaObtenerRecursosImpresion Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RespuestaObtenerRecursosImpresion)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ReimprimirCompletedEventHandler(object sender, ReimprimirCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ReimprimirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ReimprimirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuestaReimpresion Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuestaReimpresion)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AnularRangoCompletedEventHandler(object sender, AnularRangoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AnularRangoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AnularRangoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuesta Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuesta)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ObtenerEstadoCFECompletedEventHandler(object sender, ObtenerEstadoCFECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerEstadoCFECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObtenerEstadoCFECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SICFERespuestaEstadoCFE Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SICFERespuestaEstadoCFE)(this.results[0]));
        }
    }
}
